export { default as Home } from './Home';
export { default as Leaderboard } from './Leaderboard';
export { default as Lobby } from './Lobby';
export { default as Questions } from './Questions';
export { default as Score } from './Score';
export { default as Settings } from './Settings';
export { default as Student } from './Student';
export { default as Teacher } from './Teacher';
export { default as StudentLogin } from './StudentLogin';